DROP FUNCTION IF EXISTS current_school_id;
DROP FUNCTION IF EXISTS current_user_role;
DROP FUNCTION IF EXISTS current_user_id;

ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE absences DISABLE ROW LEVEL SECURITY;
ALTER TABLE marks DISABLE ROW LEVEL SECURITY;
ALTER TABLE students DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE schools DISABLE ROW LEVEL SECURITY;
