package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"strconv"

	"github.com/k/iRegistro/internal/presentation/graphql/model"
)

// Schools is the resolver for the schools field. (Note: Real implementation would need pagination/filtering)
// For now returning empty or erroring as we don't have GetSchools
func (r *queryResolver) Schools(ctx context.Context) ([]*model.School, error) {
	// Not implemented in service yet. Returning empty.
	return []*model.School{}, nil
}

// School is the resolver for the school field.
func (r *queryResolver) School(ctx context.Context, id string) (*model.School, error) {
	schoolID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id")
	}
	s, err := r.AcademicService.GetSchoolByID(uint(schoolID))
	if err != nil {
		return nil, err
	}

	// Fetch Campuses
	campusesData, err := r.AcademicService.GetCampusesBySchoolID(s.ID)
	if err != nil {
		return nil, err
	}

	var campuses []*model.Campus
	for _, c := range campusesData {
		campuses = append(campuses, &model.Campus{
			ID:      fmt.Sprintf("%d", c.ID),
			Name:    c.Name,
			Address: &c.Address,
			// Curriculums need fetching too if we want full tree
		})
	}

	city := s.City
	region := s.Region

	return &model.School{
		ID:       fmt.Sprintf("%d", s.ID),
		Name:     s.Name,
		City:     &city,
		Region:   &region,
		Campuses: campuses,
	}, nil
}

// Class is the resolver for the class field.
func (r *queryResolver) Class(ctx context.Context, id string) (*model.Class, error) {
	classID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id")
	}
	c, err := r.AcademicService.GetClassByID(uint(classID))
	if err != nil {
		return nil, err
	}

	return &model.Class{
		ID:      fmt.Sprintf("%d", c.ID),
		Grade:   c.Grade,
		Section: c.Section,
		Year:    c.Year,
		// Students, Subjects, etc. would be populated here or via field resolvers
	}, nil
}

// Student is the resolver for the student field.
func (r *queryResolver) Student(ctx context.Context, id string) (*model.Student, error) {
	studentID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id")
	}
	s, err := r.AcademicService.GetStudentByID(uint(studentID))
	if err != nil {
		return nil, err
	}

	return &model.Student{
		ID:        fmt.Sprintf("%d", s.ID),
		FirstName: s.FirstName,
		LastName:  s.LastName,
	}, nil
}

// Teacher is the resolver for the teacher field.
func (r *queryResolver) Teacher(ctx context.Context, id string) (*model.Teacher, error) {
	panic(fmt.Errorf("not implemented: Teacher - teacher"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
