// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Absence struct {
	ID          string    `json:"id"`
	Date        time.Time `json:"date"`
	Type        string    `json:"type"`
	IsJustified bool      `json:"isJustified"`
}

type AbsenceStatistics struct {
	TotalAbsences             int        `json:"totalAbsences"`
	AverageAbsencesPerStudent float64    `json:"averageAbsencesPerStudent"`
	StudentsWithHighAbsences  []*Student `json:"studentsWithHighAbsences"`
}

type Campus struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Address     *string       `json:"address,omitempty"`
	Curriculums []*Curriculum `json:"curriculums"`
}

type Class struct {
	ID          string           `json:"id"`
	Grade       int              `json:"grade"`
	Section     string           `json:"section"`
	Year        string           `json:"year"`
	Students    []*Student       `json:"students"`
	Subjects    []*Subject       `json:"subjects"`
	Coordinator *Teacher         `json:"coordinator,omitempty"`
	Statistics  *ClassStatistics `json:"statistics,omitempty"`
}

type ClassAssignment struct {
	Class        *Class `json:"class"`
	HoursPerWeek int    `json:"hoursPerWeek"`
}

type ClassStatistics struct {
	TotalStudents     int                `json:"totalStudents"`
	AverageGpa        *float64           `json:"averageGPA,omitempty"`
	SubjectAverages   []*SubjectAverage  `json:"subjectAverages"`
	AbsenceStatistics *AbsenceStatistics `json:"absenceStatistics"`
}

type Curriculum struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Code    *string  `json:"code,omitempty"`
	Classes []*Class `json:"classes"`
}

type Mark struct {
	ID      string    `json:"id"`
	Value   float64   `json:"value"`
	Type    string    `json:"type"`
	Date    time.Time `json:"date"`
	Subject *Subject  `json:"subject"`
}

type Query struct {
}

type School struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	City     *string   `json:"city,omitempty"`
	Region   *string   `json:"region,omitempty"`
	Campuses []*Campus `json:"campuses"`
}

type Student struct {
	ID        string     `json:"id"`
	FirstName string     `json:"firstName"`
	LastName  string     `json:"lastName"`
	Classes   []*Class   `json:"classes"`
	Marks     []*Mark    `json:"marks"`
	Absences  []*Absence `json:"absences"`
}

type Subject struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Code         *string `json:"code,omitempty"`
	HoursPerWeek *int    `json:"hoursPerWeek,omitempty"`
}

type SubjectAverage struct {
	Subject *Subject `json:"subject"`
	Average float64  `json:"average"`
}

type Teacher struct {
	ID               string             `json:"id"`
	Name             string             `json:"name"`
	Subjects         []*Subject         `json:"subjects"`
	ClassAssignments []*ClassAssignment `json:"classAssignments"`
	TotalHours       *int               `json:"totalHours,omitempty"`
}
