// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Absence struct {
	ID          string    `json:"id"`
	Date        time.Time `json:"date"`
	Type        string    `json:"type"`
	IsJustified bool      `json:"isJustified"`
}

type AbsenceStatistics struct {
	TotalAbsences             int        `json:"totalAbsences"`
	AverageAbsencesPerStudent float64    `json:"averageAbsencesPerStudent"`
	StudentsWithHighAbsences  []*Student `json:"studentsWithHighAbsences"`
}

type Campus struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Address     *string       `json:"address,omitempty"`
	Curriculums []*Curriculum `json:"curriculums"`
}

type Class struct {
	ID               string           `json:"id"`
	Grade            int              `json:"grade"`
	Section          string           `json:"section"`
	Year             string           `json:"year"`
	Students         []*Student       `json:"students"`
	Subjects         []*Subject       `json:"subjects"`
	Coordinator      *Teacher         `json:"coordinator,omitempty"`
	Statistics       *ClassStatistics `json:"statistics,omitempty"`
	Document15maggio *Document15May   `json:"document15maggio,omitempty"`
}

type ClassAssignment struct {
	Class        *Class `json:"class"`
	HoursPerWeek int    `json:"hoursPerWeek"`
}

type ClassStatistics struct {
	TotalStudents     int                `json:"totalStudents"`
	AverageGpa        *float64           `json:"averageGPA,omitempty"`
	SubjectAverages   []*SubjectAverage  `json:"subjectAverages"`
	AbsenceStatistics *AbsenceStatistics `json:"absenceStatistics"`
}

type Curriculum struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Code    *string  `json:"code,omitempty"`
	Classes []*Class `json:"classes"`
}

type Document struct {
	Type      string `json:"type"`
	Status    string `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type Document15May struct {
	Status      string       `json:"status"`
	LastUpdated string       `json:"lastUpdated"`
	Signatures  []*Signature `json:"signatures"`
}

type Mark struct {
	ID      string    `json:"id"`
	Value   float64   `json:"value"`
	Type    string    `json:"type"`
	Date    time.Time `json:"date"`
	Subject *Subject  `json:"subject"`
}

type PCTOCompany struct {
	Name           string  `json:"name"`
	HoursCompleted int     `json:"hoursCompleted"`
	Evaluation     *string `json:"evaluation,omitempty"`
}

type PCTOInfo struct {
	HoursCompleted int    `json:"hoursCompleted"`
	Status         string `json:"status"`
}

type PCTOProgression struct {
	TotalHours int            `json:"totalHours"`
	Companies  []*PCTOCompany `json:"companies"`
}

type PDPInfo struct {
	Exists     bool    `json:"exists"`
	LastReview *string `json:"lastReview,omitempty"`
}

type Query struct {
}

type ReportCard struct {
	Year            string               `json:"year"`
	Period          *string              `json:"period,omitempty"`
	GeneratedAt     *string              `json:"generatedAt,omitempty"`
	Subjects        []*ReportCardSubject `json:"subjects"`
	GeneralJudgment *string              `json:"generalJudgment,omitempty"`
}

type ReportCardSubject struct {
	Name     string  `json:"name"`
	Mark     float64 `json:"mark"`
	Judgment *string `json:"judgment,omitempty"`
}

type School struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	City     *string   `json:"city,omitempty"`
	Region   *string   `json:"region,omitempty"`
	Campuses []*Campus `json:"campuses"`
}

type Signature struct {
	Signer    string `json:"signer"`
	Timestamp string `json:"timestamp"`
}

type Student struct {
	ID               string           `json:"id"`
	FirstName        string           `json:"firstName"`
	LastName         string           `json:"lastName"`
	Classes          []*Class         `json:"classes"`
	Marks            []*Mark          `json:"marks"`
	Absences         []*Absence       `json:"absences"`
	ReportCards      []*ReportCard    `json:"reportCards"`
	PctoProgression  *PCTOProgression `json:"pctoProgression,omitempty"`
	OrientationHours int              `json:"orientationHours"`
	Documents        []*Document      `json:"documents"`
	Pdp              *PDPInfo         `json:"pdp,omitempty"`
	Pcto             *PCTOInfo        `json:"pcto,omitempty"`
}

type Subject struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Code         *string `json:"code,omitempty"`
	HoursPerWeek *int    `json:"hoursPerWeek,omitempty"`
}

type SubjectAverage struct {
	Subject *Subject `json:"subject"`
	Average float64  `json:"average"`
}

type Teacher struct {
	ID               string             `json:"id"`
	Name             string             `json:"name"`
	Subjects         []*Subject         `json:"subjects"`
	ClassAssignments []*ClassAssignment `json:"classAssignments"`
	TotalHours       *int               `json:"totalHours,omitempty"`
}
